name: Mkdocs
on:
  # Rebuild every day at 00:00
  schedule:
    - cron:  '0 0 * * *'
  # Or on every push as it can change output
  push:
jobs:
  'doc':
    name: 'Update Public documentation'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: 'Setup Python 3 on runner'
        uses: actions/setup-python@v2.1.4
        with:
          python-version: '3.x'
      - name: 'Build mkdocs content to site folder'
        run: |
            pip install -r .github/requirements.txt
            python .github/netdevops.py
            python .github/aristanetworks.py
            python .github/eosplus.py
            mkdocs build -f mkdocs.yml
      - name: 'Deploy last version to gh-pages'
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            user_name: 'github-actions[bot]'
            user_email: 'github-actions[bot]@users.noreply.github.com'
            publish_dir: ./site
